title: "Question Title"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for building on Pyrax! Please fill out the details below.
  - type: input
    id: discord_userid
    attributes:
      label: Discord user ID
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Describe your question in detail. 
      description: |
        For example, how do you fetch all transactions for a user with the TypeScript SDK?
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: What error, if any, are you getting?
      description: |
        If there is no error, you can leave this field blank.
    validations:
      required: false
  - type: textarea
    id: attempt
    attributes:
      label: What have you tried or looked at?  Or how can we reproduce the error?
      description: |
        Code snippets are preferred over screenshots
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu, Fedora, Windows WSL, etc.)
        - N/A
    validations:
      required: true
  - type: dropdown
    id: tool
    attributes:
      label: Which SDK or tool are you using? (if any)
      options:
        - TypeScript SDK
        - Rust SDK
        - Pyrax CLI
        - REST API
        - Indexer API
        - N/A
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Describe your environment or tooling in detail
      description: |
        Operating system, computer architecture, SDK or tool version, or anything else you feel is relevant
